### ISSUE TITLE
Reverse sorting by sign-in time triggers reverse sorting by student ID

### ISSUE THREAD

**Issue by charlestang06** [DigitalSignInMams/dashboard-web-app#19]
![Screenshot (110)](https://user-images.githubusercontent.com/75450612/228820778-f9f0dcc2-b325-4950-a99e-e3e4ac9d917a.png)

Sorts the wrong column when the sort by sign-in time button in reverse order is clicked.

**Comment by charlestang06** [comment]
same for the sign-out time column

**Comment by charlestang06** [comment]
fix for seniors too!

**Comment by Tarune28** [comment]
solution: only acs sort
