### ISSUE TITLE
Senior time comparison wrong

### ISSUE THREAD

**Issue by charlestang06** [DigitalSignInMams/dashboard-web-app#20]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/75450612/228821965-1b515e7b-486a-4a18-8def-b854699986ef.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/75450612/228822030-5ea1e44b-35dd-4072-9202-65a2aaf4fe7c.png">

I dont think this guy should be marked late.

**Comment by Tarune28** [comment]
fixed
