### ISSUE TITLE
Bug for manual entry

### ISSUE THREAD

**Issue by charlestang06** [DigitalSignInMams/dashboard-web-app#4]
![screenshot1](https://user-images.githubusercontent.com/75450612/227815429-d4fed5fa-b650-45d1-8d62-c7e89a56f403.jpg)

States "if log time button is pressed twice", however, the log time button can only be pressed once until it exits the popup window.

**Comment by Tarune28** [comment]
pressed twice for the same day, like if you use the button 2 times in the same day
