### ISSUE TITLE
Sort by ascending/descending on weekend

### ISSUE THREAD

**Issue by charlestang06** [DigitalSignInMams/dashboard-web-app#5]
When on weekend, sort by ascending/descending for sign-in/out time does not work. Stays the same where the weekend is on top.

![screenshot2](https://user-images.githubusercontent.com/75450612/227815677-8547c95a-99bb-4af4-b9ba-c18d16c3c10d.jpg)

**Comment by Tarune28** [comment]
fixed, will release on vm later tn
