### ISSUE TITLE
Verification purposes after new admin

### ISSUE THREAD

**Issue by charlestang06** [DigitalSignInMams/dashboard-web-app#6]
When **unsuccessfully** adding an admin (there is password or email error), it still sends you back to the login page for verification purposes.

Check wording of page.

![screenshot3](https://user-images.githubusercontent.com/75450612/227815899-0625d1e2-7c8b-4c4f-8fb5-3a9fb439fd08.jpg)

**Comment by Tarune28** [comment]
fixed, now only sends back to login if successful
